### ISSUE TITLE
buildout error

### ISSUE THREAD

**Issue by egon0** [frlan/partuniverse#141]
fresh jessie install. python3, buildout installed via pip3. where is the problem?

`python3 bootstrap-buildout.py
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-23.0.0.zip
Extracting in /tmp/tmpwx2e0uzu
Now working in /tmp/tmpwx2e0uzu/setuptools-23.0.0
Building a Setuptools egg in /tmp/bootstrap-e8jloe3q
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-e8jloe3q/setuptools-23.0.0-py3.4.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 199, in <module>
    ws.require(requirement)
  File "/tmp/bootstrap-e8jloe3q/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 943, in require
  File "/tmp/bootstrap-e8jloe3q/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'zc.buildout==2.5.2' distribution was not found and is required by the application`

**Comment by enko** [comment]
no need to install buildout via pip, this is actually done by the bootstrap script.

**Comment by frlan** [comment]
When having a virtualenv just run:
```
bin/pip install zc.buildout
bin/buildout 
```

**Comment by egon0** [comment]
@frlan: no, thats exactly the problem. if one installs zc.buildout manually, it dosn't bootstrap anymore with the error shown in the first post.

**Comment by frlan** [comment]
In such a case, don't call bootstrap-buildout.py -- this is what the script pretty much is doing.
