### ISSUE TITLE
Change the default SKU algorithm

### ISSUE THREAD

**Issue by enko** [frlan/partuniverse#145]
The current algorithm generates quite long strings, which are not so goood embedable into barcodes.

A better approach would be using [UUID](https://docs.python.org/3/library/uuid.html)s.

**Comment by enko** [comment]
I'm not so deep into django but if we have an ID at the point of calling the save method, we should use that to initialize the UUID:

    uuid.uuid5(uuid.NAMESPACE_URL, "https://stuff.kraut.space/pmgmt/19/")

If that is not possible, just close the issue again.

**Comment by frlan** [comment]
Not sure why this would be more useful compared to just some random uuid.

**Comment by frlan** [comment]
Also ID of item is always usable for barcodes as these are the pk in django
