### ISSUE TITLE
Add a way to bulk create new storages

### ISSUE THREAD

**Issue by frlan** [frlan/partuniverse#203]
E.g. when adding a storage with many drawers it would be a good idea to bulk create such. Usually it's a number of rows and a number of colums inside the storage. Both, rows and columns should be able to be named with numbers, letters or words (maybe created form a pattern)

**Comment by flaschenpost** [comment]
I would take this issue, with Frank's help it is almost done.

**Comment by frlan** [comment]
Merged to master
