### ISSUE TITLE
Older psycopg version needed

### ISSUE THREAD

**Issue by mase76** [frlan/partuniverse#276]
Hi!
Because you require django 2.2.20, you have to use psycopg 2.8.6. Otherwise you will run into this error:
https://github.com/psycopg/psycopg2/issues/1293
Maybe you should add this to the requirements or add it to the installation instructions.

**Comment by frlan** [comment]
Usually this is an issue with used PostgreSQL-server and base system you are running on. CAn you be more specific her?

psycopg is not part of the upstream requirements for comp. reasons

**Comment by mase76** [comment]
My base system is Debian Bullseye with PostgreSQL 13.7 It is not part of the generic requirements, but this info should be added to the instructions.

**Comment by mase76** [comment]
The issue does not persist with Django 4.
