### ISSUE TITLE
Fix warning about future.url for Django 1.9

### ISSUE THREAD

**Issue by frlan** [frlan/partuniverse#74]
On Django 1.8.x: 

/home/frlan/.virtualenvs/partuniverse/local/lib/python2.7/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

**Comment by enko** [comment]
On Django this is not a warning any more. I'm building a regex to remove all the entries, because I need this for #105
