### ISSUE TITLE
Semantic form seems not to support Textbox

### ISSUE THREAD

**Issue by frlan** [frlan/partuniverse#80]
The {{ form.as_semantic }} placeholder is not showing models.TextField-fields as e.g. on 

    description = models.TextField(_("Description"),
        blank=True,
        null=True)

This is related to e.g. #67

**Comment by enko** [comment]
As discussed via chat, this seems to originate from the fact that the field was missing from the `StoragePlaceAddView` class. 

If you find another case, please let me know.

**Comment by frlan** [comment]
Caused by another issue.
